### ISSUE TITLE
(dim ...) macro to provide indexed lists?

### ISSUE THREAD

**Issue by jarcane** [jarcane/heresy#15]
It was discussed in the other thread the possibility of some kind of syntax for directly indexing lists, ie. where `dave` is a given list `(dave 3 4)` would thus return the 4th item of the 3rd item of `dave`. 

This is of course already possible with `index*`, but one possibility that I have considered for declaring this implicit syntax is the BASIC `dim` statement. 

I had considered this as a possible candidate for a (repeat ...) type function, but possibly it could instead be used to declare a "special" list var with the properties of having it's own access syntax.

This begs the question though of whether it's actually useful without some kind of mutability or at least easy altered-copy syntax as well, akin to Things.

**Comment by jarcane** [comment]
Alternately, `dim` could instead be how to introduce vectors into the language.

**Comment by AlexKnauth** [comment]
What would this dim macro do? I googled it, but I'm still confused.  Would it define a list to be a macro, or what would it do?  Could you show me some examples?

**Comment by jarcane** [comment]
OK, so, in very very rough pseudocode, here's the template for one option:

Say we do `(dim dave '(1 2 3 4 5))`.

Underneath the hood, what this actually expands to is a syntax identifier, in Racket terms. The actual expansion of our `dim` statement looks roughly like this: 

```
(define-syntax dave
  (syntax-id-rules ()
    [(_ . rest) (index* '(1 2 3 4 5) . rest)]
    [_ '(1 2 3 4 5)}))
```
In this form, it's basically just some handy syntax sugaring. I'm pretty sure this should work too, there's some samples like this in Fear of Macros IIRC. 

In the future, the macro could possibly be expanded to allow other syntax, like maybe a copy method similar to how Things work.

**Comment by AlexKnauth** [comment]
Why not just redefine `#%app` to treat lists in function positions like that, and `#%app` could do the copy method and all that too.  A problem with the `dim` macro is that `dave` has to be a macro, and so if it's passed as an argument to a function the function won't be able to use that, and if there is a copy method, the result of that won't be able to be used in the function position, but if you redefine `#%app` you can do that without the `dim` macro.  Also with the `dim` macro you couldn't use `dave` in either apply or a higher order function, like this: `(map dave '(7 8 9))`, but with a modified `#%app` you could.

**Comment by jarcane** [comment]
It's not a bad idea. I've not really played with redefining stuff like `#%app` much, and what little I did early on made me a bit gunshy of it because it can break in all kinds of unexpected ways if you aren't careful.

Direct list indexing like that does have strong appeal; it's certainly an expected BASIC feature, and one that's often missing or poor in Lisps. To be fair, there are practical, performance reasons for this, each index operation involves tail-recursion and in big lists that gets to be very not free even in a language like Racket with good TCO, which is why the job of easily-indexable list-like structures is usually given to vectors.

Still, I like the idea. And the cool thing is we could extend it in the future if we add vectors/arrays easily; we'll already have the syntax in place.

**Comment by AlexKnauth** [comment]
How did it break?  It seems to me like the racket module system should keep it from breaking too unexpectedly.

**Comment by jarcane** [comment]
I forget precisely now. I think I had experimented with writing my own REPL for Heresy and largely failed. And it's entirely possible I simply didn't know what I was doing with it enough to make anything workable.

**Comment by jarcane** [comment]
Since this has been implemented now as an actual default behavior, I'm retiring this issue and thread.

We'll save the `dim` keyword for some other use; vectors perhaps.

**Comment by AlexKnauth** [comment]
What would `dim` be useful for if it was used for vectors?  Why couldn't you just use `def`?

**Comment by jarcane** [comment]
Not sure that it would, save perhaps if you wanted some syntax for defining a list of a specific size ahead of time. Not really useful unless they're mutable, though, or behave like mutable through some kind of clear copy syntax.

I guess it could be used for a `repeat` function, but mostly I think it's just not likely to ever go in.

**Comment by AlexKnauth** [comment]
For a list (or vector) of a specific size ahead of time, why not just `(def v (make-vector size))`?

**Comment by AlexKnauth** [comment]
And what would the `repeat` function be?

**Comment by jarcane** [comment]
For a vector of a specific size ahead of time, why not just (def v (make-vector size))?`

See rule #1: http://pkg-build.racket-lang.org/doc/heresy/index.html

Generally speaking, where names for a thing exist in BASIC, I try to use that word. `dim` in BASICs is precisely that thing, more or less: Make an array of X dimensions. So if I did provide a name to such a function, I'd want to at least consider using that.

**Comment by AlexKnauth** [comment]
Okay that makes sense.
