### ISSUE TITLE
Not possible to define an empty thing. 

### ISSUE THREAD

**Issue by jarcane** [jarcane/heresy#35]
I've been tinkering around with some monad-like experiments that have so far gone nowhere, but one thing that did appear in playing around with one of them was that it appears it's not possible to define an empty object with no fields with the current syntax. 

This is probably an easy enough fix, just want to get it in here before I forget to have a look at it.

**Comment by jarcane** [comment]
I actually had a surprising amount of difficulty parsing out what the current Thing code is doing, and wound up just giving the State thing a return new syntax instead.

Pinging @AlexKnauth since he knows the current macro system better than I.

**Comment by AlexKnauth** [comment]
What do you mean? Stuff like this works fine:
```racket
#lang heresy

(def empty-thing (thing))
(empty-thing)

(def fn point (x-value y-value)
  (thing extends empty-thing
         [x x-value]
         [y y-value]))

(def 1-2 (point 1 2))
(1-2)
```

**Comment by jarcane** [comment]
Maybe I just misunderstood the syntax? I know that `(describe Thing ())`
doesn't work, and I guess it didn't occur to me to try `(thing)` without
arguments.

**Comment by AlexKnauth** [comment]
The docs already say `(describe Name (field value) ...)`, with no parens around the field-value pairs for any case.
