### ISSUE TITLE
Bindings in state notation cannot self-reference

### ISSUE THREAD

**Issue by jarcane** [jarcane/heresy#37]
The following example will not work: 

```
#lang heresy

(do> (:= x 5)
     (:= (x) x (* x x))
     (return x))
```
Attempting to reassign a value self-referentially produces an error:
```
Documents\GitHub\heresy\lib\things.rkt:81:20: lst: undefined;
 cannot use before initialization
```
Line referenced: https://github.com/jarcane/heresy/blob/master/lib/things.rkt#L81

At a guess and tinkering with it, it seems the trouble possibly arises from the mutual references to `this` and `lst` inside the `(make-thing ...)` function. Swapping the order of their definitions causes an error reference to `this` instead.

 Possibly though there may be an issue with `(#%app)` as a previous error triggered there instead but with the same message.

**Comment by jarcane** [comment]
It's also possible of course this just means I need a better solution for the := macro as well, that the expansion's fucking up somewhere. The macro stepper's being rather unhelpful on that score.

**Comment by zenspider** [comment]
Looks like you want to generate a `let*` instead of a `let`? or am I misunderstanding the problem? You might also want to look at how `letrec` expands to a bunch of blank vars + `set!`s.

**Comment by jarcane** [comment]
Sadly that seems to make no difference, still the same error.

**Comment by jeapostrophe** [comment]
What is this program supposed to return? 25?

**Comment by jarcane** [comment]
That's the idea. 

To put it back in basic terms, think of it as the equivalent of `LET X = X * X`.

**Comment by jeapostrophe** [comment]
Some comments on your code, looking at the expansion, you are tripling the output with your expression module begin.

**Comment by jeapostrophe** [comment]
This gets the right answer and I believe is what you want:

```racket
(def macroset :=
  [(:= (name ...) var value)
   (fn (s)
     (thing extends s
            (var (let ([name (s (quote name))] ...)
                   value))))]
  [(:= var value)
   (fn (s) (thing extends s (var value)))])
```

**Comment by jeapostrophe** [comment]
The main problem with the aforementioned is that it doesn't work with stuff like
(:= (f) f (lambda (x) (f (+ x 1))))

where you want the inner f to be the new value, but in my opinion, the fact that you started with (f) means that you definitely don't want that.

**Comment by jarcane** [comment]
Hmm. I actually hadn't thought about the implications for something like passing function values like that. I'm not sure your example would work exactly anyhow. There are ways around it for recursive functions (`fnlet` was designed for that) though, and I think it's fine.

I've gone ahead and pushed your solution in https://github.com/jarcane/heresy/commit/57706d5e5c886a3260038b8c1c9fc08a49551b2f. Thank you for the assist.
