### ISSUE TITLE
A question of let vs. let*

### ISSUE THREAD

**Issue by jarcane** [jarcane/heresy#38]
At the moment, Heresy simply imports `let` as it exists in Racket, which means that it cannot reference previous bindings, just as Racket's can't. 

This leads us to a question: what do we do when we _do_ want to do that. As I see it there's two options:
1) Racket-y solution: we add a second form that binds to `let*` and/or `letrec`
2) Clojure-ish solution: make the `let*` behavior the default.
3) Possibly extreme solution: make `letrec` behavior the default.

I'm a little inclined to prefer number 2 at least, partly because I work with Clojure and find it easier, but I'm also assuming there is a justification for the separate forms in Racket, and I'm thinking it might be nice to know what those are before I make a move there.

**Comment by datagrok** [comment]
`let` vs `let*` vs `letrec` was one of the first confusing things I met when trying to learn scheme (I still haven't really.) With a sufficiently clever compiler, could you have a single `let` form which could detect which of the three behaviors is appropriate in each situation? I [asked this before](https://gist.github.com/datagrok/248149407d29e5843cec#scheme) and my lisp-expert friend thought it might be possible but didn't know of any examples.

**Comment by jeapostrophe** [comment]
None! Just have `define`!

**Comment by manuel** [comment]
Having both let and let* makes the code (slightly) more expressive: when you see a let*, you immediately know that some binding will refer to an earlier one. It's a tiny benefit.

Note that scheme also has a fourth form, letrec*, but I'm not sure I want to go there. :-)

**Comment by jarcane** [comment]
Perhaps it is my time in Scala of late, but I increasingly find myself adopting the style @jeapostrophe mentions, and that has increasingly been pushed in Racket pedagogy, of simply using `def` everywhere for local definitions. The behavior seems more predictable that way, in any case.

I won't remove `let` entirely, too much existing code depends on it, but I think for now I'm happy to leave it as-is.
