### ISSUE TITLE
Documentation link fails with error

### ISSUE THREAD

**Issue by spdegabrielle** [jarcane/heresy#48]
http://docs.racket-lang.org/heresy/index.html
Fails with error:

Racket
Page not found

> ((uncaught-exception-handler)
   (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*))))
uncaught exception: 404

**Comment by jarcane** [comment]
Ack. This is because there's still some left-over example code that doesn't work, so the Racket package server fails to build it. 
I'll push a fix in a moment and have pkg.racket rescan.

**Comment by spdegabrielle** [comment]
Thanks
